### PR TITLE
Add "wiring" capability

### PR DESCRIPTION
**Pull request by thevolatilebit**
This PR introduces the ability to explicitly establish "wires" along which information flows between different agents in a hierarchy. Note that it is possible to retrieve and modify the state of any other agent from within any agent, in any way. However, in some cases, it may be desirable to explicitly specify that certain agents observe a particular state variable of another agent.

Consider the following example:

```Julia
using AlgebraicAgents

# Define a simple hierarchy.

@aagent struct MyAgent end

alice = MyAgent("alice")
alice1 = MyAgent("alice1")
entangle!(alice, alice1)

bob = MyAgent("bob")
bob1 = MyAgent("bob1")
entangle!(bob, bob1)

joint_system = ⊕(alice, bob, name = "joint system")

# Add wires.
add_wire!(joint_system; from=alice, to=bob, from_var_name="alice_x", to_var_name="bob_x")
add_wire!(joint_system; from=bob, to=alice, from_var_name="bob_y", to_var_name="alice_y")

add_wire!(joint_system; from=alice, to=alice1, from_var_name="alice_x", to_var_name="alice1_x")
add_wire!(joint_system; from=bob, to=bob1, from_var_name="bob_x", to_var_name="bob1_x")

# Show wires.
get_wires_from(alice)
get_wires_to(alice1)
```

The wires are stored in `getopera(joint_system).wires`:

```Julia
4-element Vector{NamedTuple{(:from, :from_var_name, :to, :to_var_name), <:Tuple{AbstractAlgebraicAgent, Any, AbstractAlgebraicAgent, Any}}}:
 (from = MyAgent{name=alice, uuid=40c7fd67, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, from_var_name = "alice_x", to = MyAgent{name=bob, uuid=bedfcc68, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, to_var_name = "bob_x")
 (from = MyAgent{name=bob, uuid=bedfcc68, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, from_var_name = "bob_y", to = MyAgent{name=alice, uuid=40c7fd67, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, to_var_name = "alice_y")
 (from = MyAgent{name=alice, uuid=40c7fd67, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, from_var_name = "alice_x", to = MyAgent{name=alice1, uuid=1f2da3ab, parent=MyAgent{name=alice, uuid=40c7fd67, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}}, to_var_name = "alice1_x")
 (from = MyAgent{name=bob, uuid=bedfcc68, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}, from_var_name = "bob_x", to = MyAgent{name=bob1, uuid=1d964dad, parent=MyAgent{name=bob, uuid=bedfcc68, parent=FreeAgent{name=joint system, uuid=10348bd0, parent=nothing}}}, to_var_name = "bob1_x")
```

The new feature also integrates nicely with `getobservable`, so that one can fetch the values incoming to an agent along the wires.

```julia
# Retrieve variables along input wires.
AlgebraicAgents.getobservable(a::MyAgent, args...) = getname(a)

retrieve_input_vars(alice1)
```

```Julia
Dict{String, String} with 1 entry:
  "alice1_x" => "alice"
```

Additionally, we can plot the agents in the hierarchy, showing links between parents and children, along with the wires. This configuration can be adjusted as necessary. Let me recall that we have the possibility as well to export a hierarchy as a Mermaid diagram.

```julia
wiring_diagram(joint_system)

# Do not show edges between parents and children.
wiring_diagram(joint_system; parentship_edges=false)

# Only show listed agents.
wiring_diagram([alice, alice1, bob, bob1])

# Group agents into two clusters.
wiring_diagram([[alice, alice1], [bob, bob1]])
# Provide labels for clusters.
wiring_diagram([[alice, alice1], [bob, bob1]]; group_labels=["alice", "bob"], parentship_edges=false)
```

Note that `wiring_diagram` return the Graphviz source code as a string. You can render it online at http://magjac.com/graphviz-visual-editor/ (I suggest using dot engine).

image

image

### CODE REVIEW

**Comment by thevolatilebit** [comment]
It is now possible to combine, in a single reaction network,
- "classical species" (continuous or discrete; considered as pure quantities);
- "structured agents" (possibly with custom evolutionary function; these can appear both on LHS and RHS).

Consider the following example: 

```Julia
@push network begin
    # With specified intensities, generate experimental resources.
    ρ1, ∅ --> R1

    # Generate "Molecule 1" (where the integer corresponds to a "state" of, e.g., experimental triage).
    ρ3, ∅ --> M1(@t(), rand(4))

    # Based on properties of particular "structured agent" assigned to the transition,
    # we can update the attributes of the instance of a transition (such as probability of success).

    # Transition "Molecule 1" into "Molecule 2."
    # Update transition probability based on properties of "M1," 
    # which was assigned as a "resource" to the transition.
    ρ4,
    R1 + M1 --> M2(@t(), rand(4)),
    preAction => update_prob_transition(state, transition)

    5.0, R2 + M1 --> @structured(M2(@t(), rand(4)), :A)
    1.0, R2 + A --> @structured(M2(@t(), rand(4)), f_species(@transition))

    1.0, R2 + M1 --> @move(M1, :M2)
    1.0, R2 + M1 --> @move(M1, :C)
end
```

**Comment by slwu89** [comment]
Hi @thevolatilebit, thanks for asking me to take a look at this. Just had a few questions:

  * if setting up the wires in a programmatic way, is there some way to verify that the variables requested in each agent actually are defined? I notice in the examples we are still able to define wires between variables that do not exist in the agents.
  * I'm a little unclear on what the wires return, it looks like `retrieve_input_vars` gives a dictionary; is there a way to directly query the value that the wire is attached to?

**Comment by thevolatilebit** [comment]
It is now possible to combine, in a single reaction network,
- "classical species" (continuous or discrete; considered as pure quantities);
- "structured agents" (possibly with custom evolutionary function; these can appear both on LHS and RHS).

Consider the following example: 

```Julia
@push network begin
    # With specified intensities, generate experimental resources.
    ρ1, ∅ --> R1

    # Generate "Molecule 1" (where the integer corresponds to a "state" of, e.g., experimental triage).
    ρ3, ∅ --> M1(@t(), rand(4))

    # Based on properties of particular "structured agent" assigned to the transition,
    # we can update the attributes of the instance of a transition (such as probability of success).

    # Transition "Molecule 1" into "Molecule 2."
    # Update transition probability based on properties of "M1," 
    # which was assigned as a "resource" to the transition.
    ρ4,
    R1 + M1 --> M2(@t(), rand(4)),
    preAction => update_prob_transition(state, transition)

    5.0, R2 + M1 --> @structured(M2(@t(), rand(4)), :A)
    1.0, R2 + A --> @structured(M2(@t(), rand(4)), f_species(@transition))

    1.0, R2 + M1 --> @move(M1, :M2)
    1.0, R2 + M1 --> @move(M1, :C)
end
```

**Comment by thevolatilebit** [comment]
> Hi @thevolatilebit, thanks for asking me to take a look at this. Just had a few questions:
> 
> * if setting up the wires in a programmatic way, is there some way to verify that the variables requested in each agent actually are defined? I notice in the examples we are still able to define wires between variables that do not exist in the agents.
> * I'm a little unclear on what the wires return, it looks like `retrieve_input_vars` gives a dictionary; is there a way to directly query the value that the wire is attached to?

I appreciate your input!

- There are no specific checks (except when you eventually call `retrieve_input_vars`; you may encounter a verbose error if `getobservable` wasn't defined for the particular agent). This aligns with the general design philosophy of AlgAgents: while agents should adhere to a common interface, nearly everything can be customized to meet user's specific needs. Moreover, the "wires" could be utilized purely for visualization purposes. We could introduce something like `hasobservable`; however, I think that one could easily implement this manually if there was a need to verify the validity of the wires.

- You could use `getobservable` as follows: `getobservable(w.from, w.from_var_name)`, where `w` represents the wire.https://github.com/Merck/AlgebraicAgents.jl/blob/ad599745100d8e3618770ffab2cebcf4da52e6ad/src/wires.jl#L26-L34

**Comment by slwu89** [comment]
Thanks @thevolatilebit, that all makes sense!

**Comment by thevolatilebit** [comment]
Fixed compatibility with Agents.jl v6.0, which introduces some breaking changes.

**Pull request merged**
